### ISSUE TITLE
IF文の条件において変数と数値の比較が正しく評価されない

### ISSUE THREAD

**Issue by NasubiKT** [hra1129/msx_basic_compiler#1]
下記のコードにおいて、TRUEと評価されます。

```
10 A=4
20 IF A>191 THEN PRINT"T" ELSE PRINT"F"
```

上記実行結果で、"T"と出力されます。

**Comment by hra1129** [comment]
浮動小数点数の比較演算のコードがすっぽり抜け落ちているのを確認しました。

**Comment by hra1129** [comment]
修正完了しました。
下記のコードでテストして、期待通りの結果が得られることを確認しています。
https://github.com/hra1129/msx_basic_compiler/blob/main/msx_basic_compiler/test_back/test_compare.asc

**Comment by NasubiKT** [comment]
今、最新版のmsx_bacon.exeとBACONLDR.BINをダウンロードして、下記プログラムを実行したのですが、20行目で"T"、30行目で-1が表示されてしまいました。
もしかして、他に更新されてダウンロードする必要があるファイルがありますでしょうか。

```
10 A=4
20 IF A>191 THEN PRINT"T" ELSE PRINT"F"
30 PRINT (A>191)
```
