### ISSUE TITLE
basic_commands.txtに未記載のステートメントについて

### ISSUE THREAD

**Issue by baseballcap-mio** [hra1129/msx_basic_compiler#13]
basic_commands.txtに未記載のステートメントに関するメモです。
ざっくりとしていてすみません。

SET DATE,SET TIME,(SET VIDEO),SPC,SPRITE$,
SPRITE ON/OFF/STOP,
STOP ON/OFF/STOP,
[STRIG ON/OFF/STOP:見出しがSTICKとなっている]
TAB,WAIT

CMD,IPL

【ディスク系(あえての載せていない？)】
DSKF,FIELD,GET,INPUT #,LINE INPUT #,
LOC,LOF,MAXFILES,OPEN,PRINT #,PRINT # USING,PUT
DSKI$,DSKO$

【カセット系(CLOAD等の説明はあるので一応)】
MOTOR

【ダイレクトステートメント系(AUTO等の説明はあるので一応)】
LIST,LOAD,MERGE,NEW,RESUME,RUN,SAVE,STOP

※プリンタ関連は省略しました

本件はIssuesに相応しくないかもしれませんが、その場合は教えてください。

**Comment by hra1129** [comment]
未記載のモノは、基本的に未実装とお考え下さい。
また、WAIT命令・ダイレクトステートメント命令・プリンター系・カセットテープ系・トレース命令の
対応の予定はありません。

CMD, IPL に関しては、予約語として存在はしていますが、MSX-BASICの標準でそれら予約語を使った命令は
無いと認識しております。従って、これらのサポートの予定もありません。

ディスク系は、現在鋭意実装中です。

PRINT TAB() は対応しています。

以上で、回答になってますでしょうか？

**Comment by baseballcap-mio** [comment]
了解しました。
ありがとうございます。
