### ISSUE TITLE
BASICファイルとASCIIファイルのコンパイルについて

### ISSUE THREAD

**Issue by baseballcap-mio** [hra1129/msx_basic_compiler#14]
同一プログラムを、
(1) BASICファイルとしてSAVE
(2) ASCIIファイルとしてSAVE
上記のものをそれぞれコンパイルすると(1)はコンパイル失敗、(2)はコンパイル成功となる場合がある。
今回、具体的にはSET PAGE文,DATA文が(1)の場合のみエラーとなる。
(1)と(2)の処理の実装を別々に行っているのであれば問題はないが、(1)用の処理の実装を忘れている可能性があるので、念の為に記しておく。
念の為、ソースコードを貼っておく。

100 '
110 CLEAR 256,&HBFFF
120 AD=&HC000:DEFUSR=AD
130 READ D$:IF D$="**" THEN 160
140 POKE AD,VAL("&H"+D$)
150 AD=AD+1:GOTO 130
160 '
170 SCREEN 5
180 CH=ASC("A")
190 FOR I=1 TO 3
200  SET PAGE 0,I
210  FOR J=0 TO &H6000 STEP &H2000
220   POKE &HC001,CH:A=USR(0)
230   FOR K=0 TO 7
240    VPOKE J+K,PEEK(&HFC40+K)
250   NEXT
260   CH=CH+1
270  NEXT
280 NEXT
290 '
300 SCREEN 4
310 FOR I=4 TO 15
320  VDP(4)=I*4+3
330  TIME=0
340  IF TIME<6 THEN 340
350 NEXT
360 END
370 '
380 DATA 3E,00
390 DATA DD,21,05,01
400 DATA CD,5F,01
410 DATA C9,**

**Comment by hra1129** [comment]
BASICファイルを直接コンパイルする処理は、暫定的に入っていますが、現在ペンディングとさせていただいています。
まずは、ASCIIファイルをコンパイルする処理で、一通りの機能を実装してから、BASICファイルへの対応を
修正していく予定ですので、もうしばらくお待ちください。

2024年3月8日現在、BASICファイルの直接コンパイル機能はまともに機能しない、とお考えいただけると助かります。

**Comment by baseballcap-mio** [comment]
了解しました。
ありがとうございます。
