### ISSUE TITLE
DATA lines throw syntax error

### ISSUE THREAD

**Issue by zmajcenic** [hra1129/msx_basic_compiler#22]
All DATA lines throw syntax error.
Is DATA statement supported ?

**Comment by hra1129** [comment]
100 DEFINT A-Z:SCREEN 1:COLOR 15,4,7
110 READ A$,B:IF A$="*" THEN 130
120 PRINT "[";A$;"]";B:GOTO 110
130 DATA "HELLO", 100, "WORLD!!", 200, "I love MSX.", 300, "*", 0

![image](https://github.com/user-attachments/assets/6075d15f-a40f-44d2-8fd9-41d1d4320845)

![image](https://github.com/user-attachments/assets/97ceac4d-f5e1-4457-9296-4763be6093a1)

It is working fine at my place.
Maybe there is a bug outside of the DATA statement that is causing the error in the DATA statement.
If you could provide a simple code where the error occurs, it would help us to analyze the situation.

**Comment by zmajcenic** [comment]
Thanks, this was also caused by trying to compile .BAS instead of .ASC

**Comment by hra1129** [comment]
With the recent release, we now officially support reading intermediate code formats.
Try it out and see if it does what you want it to do.

**Comment by zmajcenic** [comment]
DATA lines are correctly handled now

**Comment by hra1129** [comment]
Thanks!
