### ISSUE TITLE
累乗の計算が正しくない

### ISSUE THREAD

**Issue by NasubiKT** [hra1129/msx_basic_compiler#7]
下記サンプルコードにおいて、計算結果が128(2の7乗)と計算されるところ、49(7の2乗)と計算される。
```
10 PRINT 2^7
```

**Comment by NasubiKT** [comment]
ありがとうございます。
整数・浮動小数ともに累乗の計算結果を確認いたしました。
このISSUEはCLOSEいたします。

**Comment by NasubiKT** [comment]
申し訳ありません。再OPENします。
以下のサンプルコードで、20行目は128となるのですが、50行目が49となります。

```
10 DEFINTA-Z
20 PRINT 2^7
30 BM=0:IV=0
40 BM=2^(7-(IV MOD 8))
50 PRINT BM
```

**Comment by hra1129** [comment]
失礼しました。
演算命令は、HL 演算子 DE な演算が殆どなのに、INTEXP は DE ^ HL なのが抜け落ちてました。
最適化バグの修正と称して DE:HL入れ替えミスして上手くいっていたのもこれ。
修正しました。今度こそ大丈夫だとおもいます。

**Comment by NasubiKT** [comment]
ありがとうございます。
2つ目のサンプルコードでの動作を確認いたしました。
このISSUEはCLOSEさせて頂きます。
