### ISSUE TITLE
PSETの異常

### ISSUE THREAD

**Issue by hra1129** [hra1129/msx_basic_compiler#9]
10 SCREEN 2,2
20 COLOR 15,5,15
30 PSET(128,96)
40 IF INKEY$="" THEN 40
50 END

【問題点１】(128,96) と指定しているのに (128,128) あたりに点が打たれる。
【問題点２】打たれる点の色がおかしい。
【問題点３】１回目の実行と２回目の実行で打たれる点の色が異なる。

参考
https://twitter.com/baseballcap_mio/status/1764412808454881545

**Comment by baseballcap-mio** [comment]
【問題点２】について
20行目のCOLOR文が反映されず、実行直後のBAKCLR(F3EAH)が反映されるらしい。
COLOR文自体は実行されているので、本テストプログラムを２回続けて実行すると、実行２回目のPSETでうたれる点の色は、初回のCOLOR文で指定された背景色となる。

**Comment by hra1129** [comment]
【問題点1】について、ソースコードを確認したところ、色指定を省略したときに Yに指定された値を計算すべきところで、
Xに指定された値を再度計算する記述になっていました。
まずは、これについて修正したモノをチェックインしました。

**Comment by hra1129** [comment]
【問題点２】について、PSET と PRESET の挙動が入れ替わっていたのが原因でした。これも修正したモノをチェックインしました。

**Comment by hra1129** [comment]
【問題点3】は、【問題点2】の修正とともに直りました。

ということで、この件について全て解決したつもりです。ご確認下さい。

**Comment by baseballcap-mio** [comment]
正常に動作することを確認しました。
ご苦労様でした。

**Comment by hra1129** [comment]
ありがとうございます。closeします。
